### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by mhendu** [acoustid/acoustid-server#50] opened 2020-09-06 06:20 UTC
Track lookups result in 'internal server error.' Not sure if this is the correct place to post this, or if anyone is actively maintaining, but since I couldn't find clear guidance this seemed like the best spot. The status page shows everything is working correctly but I'm unable to get new fingerprints or look up existing AcoustIDs.

**Comment by AlexLopezPedrosa** [comment] 2020-10-22 09:38
Did you solve this? Because I'm having the same issue.

**Comment by gaston-senac** [comment] 2020-11-18 06:41
I'm having a similar error when using Picard on a Mac (all software updated to latest version). I'm scanning some files and trying to submit the AcoustIDs

E: 19:37:29,424 webservice/__init__._handle_reply:445: Network request error for http://api.acoustid.org:80/v2/submit: Error transferring http://api.acoustid.org:80/v2/submit - server replied: INTERNAL SERVER ERROR (QT code 401, HTTP code 500)
E: 19:37:29,426 acoustid/manager._batch_submit_finished:137: AcoustID submission failed with error 'Error transferring http://api.acoustid.org:80/v2/submit - server replied: INTERNAL SERVER ERROR': internal error

**Comment by sampsyo** [comment] 2020-12-08 12:52
Hello! I believe the root cause is gzipped requests. Some enterprising Python library users sorted it out here: https://github.com/beetbox/pyacoustid/issues/62#issuecomment-740022036

**Closed** 2023-05-07 10:49 UTC
